### ISSUE TITLE
Extraction from the english wikipedia

### ISSUE THREAD

**Issue by KatharinaLB** [larsmoe/statement_extraction_wikipedia#1]
I tried the statement extraction with english articles. Therefore, I changed the URL in the wiki_API_request (https://en.wikipedia.org/w/api.php). But it doens't work with english Page IDs.

Line 84, in create_dict_of_rv_ids
    for revision in request_json["query"]["pages"][str(pageid)]["revisions"]:

KeyError: 'revisions'

What else do I have to adapt or change? Could you advise?

Thank you, 
Katharina

**Comment by larsmoe** [comment]
Hey Katharina,

I added a try-exception statement that prints out the returned json file from Wikipedia. So now there shouldn't be any errors anymore, instead now it prints the problems on the console, but run through anyway. As far as I tested it works with English articles as well. Is it possible that there some errors in your pageids? The pageids are different for different language versions of Wikipedias.

Best,
Lars

**Comment by KatharinaLB** [comment]
Hey Lars, 
thanks a lot for your quick respond and your help! Yes, you're right - It runs through but it creates an empty excel sheet and shows "Wrong page id". What do you mean by different pageids in different language versions? I already took the pageids from english articles.Is there anything else I shpuld consider?

(This is the pageid of the english article "Willis Tower" )
total number of articles: 1
{
    "batchcomplete": "",
    "limits": {
        "revisions": 500
    },
    "query": {
        "pages": {
            "28176": {
                "missing": "",
                "pageid": 28176
            }
        }
    }
}
total number of revisions: 0
wrong pageid:28176

Thank you,
Katharina

**Comment by larsmoe** [comment]
Looks like there is mistake with the API request:
{
"batchcomplete": "",
"limits": {
"revisions": 500
},
"query": {
"pages": {
"28176": {
"missing": "",
"pageid": 28176
}
}
}
}
This means there is no page with this pageid in the corresponding Wikipedia. But I checked your pageid and it is the corecct pageid for the article Willis Tower of the English Wikipedia. I assume however that you use at some point a request to a different language version of Wikipedia and in this language version the pageid 28176 does not exist. Do you use the Wiki_API_requests from this project? If so, are sure that you changed the URL in all four requests to the English Wikipedia?

**Comment by KatharinaLB** [comment]
Yes. In the Wiki_API_requests the def test_everything() is running with the english pageids (as you can see below). That's why I tought I forgot to adapt something in the create_excel_of_extracts as it doesn't recognize the english wikipedia. 
...
{
    "batchcomplete": "",
    "query": {
        "pages": {
            "28176": {
                "contentmodel": "wikitext",
                "lastrevid": 1002148967,
                "length": 60865,
                "ns": 0,
                "pageid": 28176,
                "pagelanguage": "en",
                "pagelanguagedir": "ltr",
                "pagelanguagehtmlcode": "en",
                "title": "Willis Tower",
                "touched": "2021-02-02T00:57:52Z"
            }
...

**Comment by larsmoe** [comment]
Honeslty I am kind of confused, because when I try it i just run through without any problems. I justed pushed it again, so maybe you try to pull it again. I also changed the test_everything in the Wiki_API_request. Maybe you try it again now, because I updated it in a way that all examples are from the Willis Tower. I would suggest that you run the wiki_API_requests once for each test case (meaning you comment out all but one line from the lines 89-92). 
Then for line 89 ypu should get:
{
    "continue": {
        "continue": "||",
        "rvcontinue": "20060623095637|60147540"
    },
    "limits": {
        "revisions": 500
    },
    "query": {
        "pages": {
            "28176": {
                "ns": 0,
                "pageid": 28176,
                "revisions": [
                    {
                        "parentid": 363371442,
                        "revid": 363371475,
                        "timestamp": "2001-09-18T16:43:27Z"
                    },

**Comment by larsmoe** [comment]
I only copy the first few lines, if you run it you will get much longer outouts
For line 90:
{
    "continue": {
        "continue": "||",
        "rvcontinue": "20070501183516|127481259"
    },
    "limits": {
        "revisions": 500
    },
    "query": {
        "pages": {
            "28176": {
                "ns": 0,
                "pageid": 28176,
                "revisions": [
                    {
                        "parentid": 60123006,
                        "revid": 60147540,
                        "timestamp": "2006-06-23T09:56:37Z"
                    },

**Comment by larsmoe** [comment]
line 91:
{
    "parse": {
        "pageid": 28176,
        "revid": 363371475,
        "text": {
                     "*": "<div class=\"mw-parser-output\"><p>Describe the new page here.\n</p>\n<!-- \nNewPP limit report\nParsed by mw1285\nCached time: 20210202115552\nCache expiry: 2592000\nDynamic content: false\nComplications: 
                  },
        "title": "Willis Tower"
    }

**Comment by larsmoe** [comment]
and for line 92:
{
    "batchcomplete": "",
    "query": {
        "pages": {
            "28176": {
                "contentmodel": "wikitext",
                "lastrevid": 1002148967,
                "length": 60865,
                "ns": 0,
                "pageid": 28176,
                "pagelanguage": "en",
                "pagelanguagedir": "ltr",
                "pagelanguagehtmlcode": "en",
                "title": "Willis Tower",
                "touched": "2021-02-02T00:57:52Z"
            }
        }
    }
}

**Comment by larsmoe** [comment]
If you get the same outputs everything should work, as in the other file there is nothing, which only works for specific language versions

**Comment by KatharinaLB** [comment]
After trying it step by step I finally got results! Thank you very much!
